### ISSUE TITLE
Missing Icon: [App] GUVCView - [DE] Cinnamon

### ISSUE THREAD

**Issue by pman83** [NitruxSA/compass-icons#27]
Icon:
![guvcview](https://cloud.githubusercontent.com/assets/2750208/5767098/7df59c2a-9d06-11e4-9c29-959c8eeabee9.png)

Screenshot (Linux Mint Menu):
![bildschirmfoto vom 2015-01-15 22 33 45](https://cloud.githubusercontent.com/assets/2750208/5767122/a57c3f42-9d06-11e4-9a3d-5fbaedf06849.png)

Description:
GTK Webcam Viewer

Launcher Information:
[Desktop Entry]
Name=guvcview
GenericName=GTK UVC video viewer
X-GNOME-FullName=GTK UVC video viewer
X-GNOME-FullName[cs]=Prohlížeč videa GTK UVC
X-GNOME-FullName[de]=UVC-Video-Betrachter in GTK
X-GNOME-FullName[en_AU]=GTK UVC video viewer
X-GNOME-FullName[es]=Reproductor video GTK UVC
X-GNOME-FullName[fr]=Logiciel GTK de visualisation de vidéo UVC
X-GNOME-FullName[it]=GTK UVC visualizzatore video
X-GNOME-FullName[lv]=GTK UVC video skatītājs
X-GNOME-FullName[nl]=GTK UVC videokijker
X-GNOME-FullName[pt]=Visualizador de vídeo GTK UVC
X-GNOME-FullName[ru]=GTK UVC видео обозреватель
X-GNOME-FullName[si]=GTK UVC වීඩියෝ දකින්නා
X-GNOME-FullName[sr]=ГТК УВЦ видео приказивач
X-GNOME-FullName[tr]=GTK UVC video görüntüleyici
Comment=A video viewer and capturer for the linux uvc driver
TryExec=guvcview
Exec=guvcview
Icon=/usr/share/pixmaps/guvcview/guvcview.png
Terminal=false
Type=Application
Categories=Video;AudioVideo;
X-GNOME-Gettext-Domain=guvcview
StartupNotify=true

**Comment by UriHerrera** [comment]
*guvcview* is already included in Compass. As you can see from the .desktop file information it uses hardcoded icon path. Edit it manually or use the icon fixer.

**Comment by pman83** [comment]
Thanks for the info. I'll try to edit it manually
