### ISSUE TITLE
Missing Icon: [App] Meshlab - [DE] Cinnamon

### ISSUE THREAD

**Issue by pman83** [NitruxSA/compass-icons#28]
Icon:
![meshlab](https://cloud.githubusercontent.com/assets/2750208/5767182/51be665e-9d07-11e4-82e5-a3de0c8b2afb.png)

Screenshot:
![bildschirmfoto vom 2015-01-15 22 39 29](https://cloud.githubusercontent.com/assets/2750208/5767210/76c023ac-9d07-11e4-9361-ab48bfcb0117.png)

Description:
Show, edit & repair polygon structures and 3d models.

Launcher Information:
[Desktop Entry]
Version=1.0
Name=MeshLab
Name[en_GB]=MeshLab
GenericName=Mesh processing
GenericName[en_GB]=Mesh processing
Comment=View and process meshes
Type=Application
Exec=meshlab
Icon=/usr/share/pixmaps/meshlab_32x32.xpm
Terminal=false
MimeType=model/mesh;application/x-3ds;image/x-3ds;model/x-ply;application/sla;model/x-quad-object;model/x-geomview-off;application/x-cyclone-ptx;application/x-vmi;application/x-bre;model/vnd.collada+xml;model/openctm;application/x-expe-binary;application/x-expe-ascii;application/x-xyz;application/x-gts;chemical/x-pdb;application/x-tri;application/x-asc;model/x3d+xml;model/x3d+vrml;model/vrml;model/u3d;model/idtf;
Categories=Graphics;3DGraphics;Viewer;Qt;

**Comment by UriHerrera** [comment]
*meshlab* is already included in Compass. As you can see from the .desktop file information it uses hardcoded icon path. Edit it manually or use the icon fixer.
