### ISSUE TITLE
Missing Icon: [App] Viber - [DE] Cinnamon

### ISSUE THREAD

**Issue by DoctorChe** [NitruxSA/compass-icons#39]
Icon:
![viber](https://cloud.githubusercontent.com/assets/12997590/8279390/cb9c58ea-18dc-11e5-8128-f597054f7f18.png)

[Desktop Entry]
Name=Viber
Comment=Viber VoIP and messenger
Exec=/opt/viber/Viber
Icon=/usr/share/pixmaps/viber.png
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Network;Application;
Path=

![yandex browser in docky](https://cloud.githubusercontent.com/assets/12997590/8279400/e0760248-18dc-11e5-9e31-1f5a3b894c13.png)

**Comment by UriHerrera** [comment]
There is a Viber icono included, please editor its launcher.

**Comment by DoctorChe** [comment]
Thanks!
